export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';

export const CHECK_SESSION = 'CHECK_SESSION';
export const CHECK_SESSION_SUCCESS = 'CHECK_SESSION_SUCCESS';
export const CHECK_SESSION_FAILED = 'CHECK_SESSION_FAILED';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILED = 'SIGNUP_USER_FAILED';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const VERIFY_PHONE = 'VERIFY_PHONE';
export const VERIFY_PHONE_SUCCESS = 'VERIFY_PHONE_SUCCESS';
export const VERIFY_PHONE_FAILED = 'VERIFY_PHONE_FAILED';

export const CHECK_SMS_CODE = 'CHECK_SMS_CODE';
export const CHECK_SMS_CODE_SUCCESS = 'CHECK_SMS_CODE_SUCCESS';
export const CHECK_SMS_CODE_FAILED = 'CHECK_SMS_CODE_FAILED';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILED = 'LOGOUT_USER_FAILED';

export const DRIVER_REQUEST = 'DRIVER_REQUEST';
export const DRIVER_REQUEST_SUCCESS = 'DRIVER_REQUEST_SUCCESS';
export const DRIVER_REQUEST_FAILED = 'DRIVER_REQUEST_FAILED';

export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const UPDATE_PREFRENCES = 'UPDATE_PREFRENCES';

//VEHICLE ACTIONS
export const NEARBY_VEHICLES = 'NEARBY_VEHICLES';

export const GET_VEHICLES = 'GET_VEHICLES';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS';
export const GET_VEHICLES_FAILED = 'GET_VEHICLES_FAILED';

export const GET_ONE_VEHICLE = 'GET_ONE_VEHICLE';
export const GET_ONE_VEHICLE_SUCCESS = 'GET_ONE_VEHICLE_SUCCESS';
export const GET_ONE_VEHICLE_FAILED = 'GET_ONE_VEHICLE_FAILED';

export const GET_VEHICLE_TYPES = 'GET_VEHICLE_TYPES';
export const GET_VEHICLE_TYPES_SUCCESS = 'GET_VEHICLE_TYPES_SUCCESS';
export const GET_VEHICLE_TYPES_FAILED = 'GET_VEHICLE_TYPES_FAILED';

export const GET_VEHICLE_MAKES = 'GET_VEHICLE_MAKES';
export const GET_VEHICLE_MAKES_SUCCESS = 'GET_VEHICLE_MAKES_SUCCESS';
export const GET_VEHICLE_MAKES_FAILED = 'GET_VEHICLE_MAKES_FAILED';

export const GET_VEHICLE_MAKE_MODELS = 'GET_VEHICLE_MAKE_MODELS';
export const GET_VEHICLE_MAKE_MODELS_SUCCESS = 'GET_VEHICLE_MAKE_MODELS_SUCCESS';
export const GET_VEHICLE_MAKE_MODELS_FAILED = 'GET_VEHICLE_MAKE_MODELS_FAILED';

export const ADD_VEHICLE = 'ADD_VEHICLE';
export const ADD_VEHICLE_SUCCESS = 'ADD_VEHICLE_SUCCESS';
export const ADD_VEHICLE_FAILED = 'ADD_VEHICLE_FAILED';

export const UPDATE_VEHICLE = 'UPDATE_VEHICLE';
export const UPDATE_VEHICLE_SUCCESS = 'UPDATE_VEHICLE_SUCCESS';
export const UPDATE_VEHICLE_FAILED = 'UPDATE_VEHICLE_FAILED';

//TRIPS ACTONS
export const INITIATE_TRIP = 'INITIATE_TRIP';
export const TRIP_CANCELED = 'TRIP_CANCELED';
export const TRIP_RECEIVED = 'TRIP_RECEIVED';
export const TRIP_TIMEOUT = 'TRIP_TIMEOUT';

export const TRIP_ACCEPTED = 'TRIP_ACCEPTED';
export const TRIP_IN_PROGRESS = 'TRIP_IN_PROGRESS';
export const TRIP_FINISHED = 'TRIP_FINISHED';

export const GET_MY_TRIPS = 'GET_MY_TRIPS';
export const GET_MY_TRIPS_SUCCESS = 'GET_MY_TRIPS_SUCCESS';
export const GET_MY_TRIPS_FAILED = 'GET_MY_TRIPS_FAILED';

export const GET_NEARBY_TRIPS = 'GET_NEARBY_TRIPS';
export const GET_NEARBY_TRIPS_SUCCESS = 'GET_NEARBY_TRIPS_SUCCESS';
export const GET_NEARBY_TRIPS_FAILED = 'GET_NEARBY_TRIPS_FAILED';

export const GET_ONE_TRIP = 'GET_ONE_TRIP';
export const GET_ONE_TRIP_SUCCESS = 'GET_ONE_TRIP_SUCCESS';
export const GET_ONE_TRIP_FAILED = 'GET_ONE_TRIP_FAILED';

export const CREATE_TRIP = 'CREATE_TRIP';
export const CREATE_TRIP_SUCCESS = 'CREATE_TRIP_SUCCESS';
export const CREATE_TRIP_FAILED = 'CREATE_TRIP_FAILED';

export const EDIT_TRIP = 'EDIT_TRIP';
export const EDIT_TRIP_SUCCESS = 'EDIT_TRIP_SUCCESS';
export const EDIT_TRIP_FAILED = 'EDIT_TRIP_FAILED';

export const GET_FAV_PLACES = 'GET_FAV_PLACES';
export const GET_FAV_PLACES_SUCCESS = 'GET_FAV_PLACES_SUCCESS';
export const GET_FAV_PLACES_FAILED = 'GET_FAV_PLACES_FAILED';

export const ADD_FAV_PLACE = 'ADD_FAV_PLACE';
export const ADD_FAV_PLACE_SUCCESS = 'ADD_FAV_PLACE_SUCCESS';
export const ADD_FAV_PLACE_FAILED = 'ADD_FAV_PLACE_FAILED';

export const DELETE_FAV_PLACE = 'DELETE_FAV_PLACE';
export const DELETE_FAV_PLACE_SUCCESS = 'DELETE_FAV_PLACE_SUCCESS';
export const DELETE_FAV_PLACE_FAILED = 'DELETE_FAV_PLACE_FAILED';

export const BACK_TO_TRIP = 'BACK_TO_TRIP';

//SETTINGS
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION';
